apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-payment-service
  template:
    metadata:
      labels:
        app: go-payment-service
    spec:
      containers:
        - name: go-payment-app
          image: irrefl/go-payment-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: go-payment-service-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 3000
  selector:
    app: go-payment-service